### PR TITLE
warning fix

### PR DESCRIPTION
**Pull request by chandraprakash**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/message_filter/27)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @dirvine

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by chandraprakash** [comment]
@rossmuir  can you help with build failure on travis-ci osx

**Comment by rossmuir** [comment]
Sure I will update the travis.yml file

**Comment by chandraprakash** [comment]
@rossmuir  may be you can review this one from qi 
https://github.com/maidsafe/message_filter/pull/26

**Comment by rossmuir** [comment]
:-) didn't see Qi's I have just submitted a very similar one - https://github.com/maidsafe/message_filter/pull/29 - I only had beta in my Matrix - now you have choices...

**Comment by dirvine** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/message_filter/27)

**Pull request merged**
