### PR TITLE
Initial run of RustFmt

### PR DESCRIPTION
**Pull request by drrosa**
**Code Bounty task**
Initial run of RustFmt on libraries that are not being worked on at the moment.

**My bitcoin address:** 1KfJGj4j8iYdywwgZGkwsVZngaSXkTX6XL

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/message_filter/35)

### CODE REVIEW

**Comment by drrosa** [comment]
Hi @chandraprakash, just wanted to let you know my PR didn't get automatically assigned to anyone.

**Comment by NickLambert** [comment]
Payment made. Thank you!

**Comment by drrosa** [comment]
You´re welcome. Thank you.

**Pull request merged**
